# Generated by Django 4.2.3 on 2023-07-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addus',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
